services: 
  db: 
    image: docker.io/postgres:15-alpine
    volumes: 
      - customer_db:/var/lib/postgresql/data/pgdata
    env_file: 
      - .env
    ports:
      - 5432:5432
    networks: 
      - tcc-network

  prestart:
      build:
        context: .
      networks:
        - tcc-network
      depends_on:
        - db
      command: sh scripts/prestart.sh
      env_file:
        - .env

  backend: 
    build:
      context: .
    ports: 
      - 8000:8000
    networks:
      - tcc-network
    depends_on: 
      - db
    env_file: 
      - .env  

volumes: 
  customer_db:

networks:
  tcc-network: 
    driver: bridge