services: 
  db: 
    image: docker.io/postgres:15-alpine
    volumes: 
      - customer-db:/var/lib/postgresql/data/pgdata
    env_file: 
      - .env
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    networks: 
      - tcc-network

  prestart:
      build:
        context: .
      networks:
        - tcc-network
      depends_on:
        - db
      command: sh scripts/prestart.sh
      env_file:
        - .env
      environment:
        - POSTGRES_SERVER=db
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER?Variable not set}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

  backend: 
    build:
      context: .
    ports: 
      - 8000:8000
    networks:
      - tcc-network
    depends_on: 
      - db
    env_file: 
      - .env  
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}

volumes: 
  customer-db:

networks:
  tcc-network: 
    driver: bridge